title: Hugo Dias 🇵🇹 ![Myself](/assets/eosr6147.jpg)
description: Hey there 🖐️
plugins:
  - jekyll-relative-links
theme: jekyll-theme-primer
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
minima:
  skin: dark