title: [Hugo Dias]
description: [Personal Bio]
plugins:
  - jekyll-relative-links
theme: jekyll-theme-slate
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
minima:
  skin: dark